@isTest
public class AuditAppReportControllerTest {

   /* @isTest static void testClearDataforReport() {
        
        Test.startTest();
        AuditAppReportController.ClearDataforReport();
        Test.stopTest();
 
        Integer auditHistoryCount = [SELECT COUNT() FROM Audithistory__c];
               System.assertNotEquals('System Administrator',null);
    }

    @isTest static void testUnusedProfileDataforReport() {
         
        Test.startTest();
        AuditAppReportController.unusedProfileDataforReport();
        Test.stopTest();
 
        Integer auditHistoryCount = [SELECT COUNT() FROM Audithistory__c];
                System.assertNotEquals('System Administrator',null);
    }
    
     @isTest static void testunusedPermissionsetsDataforReport() {
        
        Test.startTest();
        AuditAppReportController.unusedPermissionsetsDataforReport();
        Test.stopTest();
 
        Integer auditHistoryCount = [SELECT COUNT() FROM Audithistory__c];
               System.assertNotEquals('System Administrator',null);
    }
    @isTest static void testPermissionSetGroupsDataforReport() {
        
        Test.startTest();
        AuditAppReportController.PermissionSetGroupsDataforReport();
        Test.stopTest();
 
        Integer auditHistoryCount = [SELECT COUNT() FROM Audithistory__c];
                System.assertNotEquals('System Administrator',null);
    }

     @isTest static void testrolesDataforReport() {
        
        Test.startTest();
        AuditAppReportController.rolesDataforReport();
        Test.stopTest();
         Integer auditHistoryCount = [SELECT COUNT() FROM Audithistory__c];
              System.assertNotEquals('System Administrator',null);
    }
        @isTest static void testpublicGroupsDataforReport() {
         
        Test.startTest();
        AuditAppReportController.publicGroupsDataforReport();
        Test.stopTest();

        
        Integer auditHistoryCount = [SELECT COUNT() FROM Audithistory__c];
                System.assertNotEquals('System Administrator',null);
    }
     @isTest static void testinternalrolesDataforReport() {
        
       
        Test.startTest();
        AuditAppReportController.internalrolesDataforReport();
        Test.stopTest();
 
        Integer auditHistoryCount = [SELECT COUNT() FROM Audithistory__c];
                System.assertNotEquals('System Administrator',null);
    }*/
    
}